test

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -16,7 +16,7 @@ jobs:
       - name: Setup Python
         uses: actions/setup-python@v3
         with:
-          python-version: "3.13" # Specify a stable Python version
+          python-version: "3.13" # Specify a stable Python versionon version
 
       - name: Cache Python Dependencies
         uses: actions/cache@v3
@@ -42,6 +42,10 @@ jobs:
           fi
           if [ ! -f ./requirements.txt ]; then
             echo "Error: requirements.txt is missing!"
+            exit 1
+          fi
+          if [ ! -f ./.python-version ]; then
+            echo "Error: .python-version is missing!"
             exit 1
           fi
 
